#!/bin/bash

#################################################################################################
# Take this from existing profile
# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.bin" ] ; then
    PATH="$HOME/.bin:$PATH"
fi
PATH="$HOME/bin:$PATH"

# source everything from ~/.bash
for f in ~/.bash/*; do source $f; done

export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx
export TERM="xterm-256color"

#define preferred tools
export EDITOR=vim
export PAGER=less

# Alias to save key stroke
alias l='ls'
alias ll='ls -l'
#long list of ls
alias lf='ls -CF'
#colors and file type
alias lx='ls -lXB'
#sorted by file extension
alias lk='ls -lSr'
#sorted by size
alias lt="ls -ltr"
#sorted by date
alias la="ls -a"
#show hidden files
alias lla="ls -al"
alias psgrep="ps aux | grep "
alias dockgrep="docker ps | grep "
alias ..="cd .."
alias ...="cd ../.."
alias .3="cd ../../.."
alias .4="cd ../../../.."
alias .5="cd ../../../../../"
alias h="history"
alias e="emacsclient -t"
alias gs="git s"
alias gp="git pl"
alias gps="git ps"
alias gd="git d"
alias gc="git cv"
alias gco="git o"
alias ga="git a ."
alias gb="git b"
alias e="emacsclient -t $1"

tm() {
  [[ -z "$1" ]] && { echo "usage: tm <session>" >&2; return 1; }
  tmux has -t $1 && tmux attach -d -t $1 || tmux new -s $1
}

start() {
  tmux-session restore;
  emacs --daemon
}

reemc (){
  emacsclient -e "(kill-emacs)"
  emacs --daemon
}

[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh
[ -f /usr/share/autojump/autojump.sh ] && . /usr/local/etc/autojump.sh

# bash completion
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

# adding autojump and color
parse_git_branch() {
 git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}
sysname=`uname`
if [[ "$sysname" == 'Linux' ]]; then
   # preferred color for guest
   export PS1="\[\e[34;1m\]\u@\h - \[\e[33;1m\]\t \[\e[31;1m\]\w \[\e[35;1m\]\$(__git_ps1)\[\e[32;1m\]\\n\$\[\e[39;0m\] "
   [[ $PS1 && -f /usr/share/bash-completion/bash_completion ]] && \
       . /etc/bash_completion
else
  # Prompt colour configuration
  # preferred color for host
  export PS1="\[\e[35;1m\]\u@\h - \[\e[32;1m\]\t \[\e[31;1m\]\w \[\e[34;1m\]\$(__git_ps1)\[\e[32;1m\]\\n\$\[\e[36;1m\] "
if [ -f $(brew --prefix)/etc/bash_completion ]; then
   . $(brew --prefix)/etc/bash_completion
fi
fi

# enable bash completion in interactive shells
if ! shopt -oq posix; then
 if [ -f /usr/share/bash-completion/bash_completion ]; then
   . /usr/share/bash-completion/bash_completion
 elif [ -f /etc/bash_completion ]; then
   . /etc/bash_completion
 fi
fi

export PATH="/usr/local/sbin:$PATH"

# Predictable SSH authentication socket location.
SOCK="/tmp/ssh-agent-$USER-screen"
if test $SSH_AUTH_SOCK && [ $SSH_AUTH_SOCK != $SOCK ]
then
    rm -f /tmp/ssh-agent-$USER-screen
    ln -sf $SSH_AUTH_SOCK $SOCK
    export SSH_AUTH_SOCK=$SOCK
fi
export PATH="$HOME/bin:$HOME/.local/bin:$PATH:/usr/local/go/bin:/repos/go/bin:/repos/env/deploy"
export GOPATH="/repos/go"

if [ -f "/etc/bash_completion.d/docker" ]; then
   /etc/bash_completion.d/docker
fi

_ssh()
{
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    opts=$(grep '^Host' ~/.ssh/config | grep -v '[?*]' | cut -d ' ' -f 2-)

    COMPREPLY=( $(compgen -W "$opts" -- ${cur}) )
    return 0
}

complete -F _ssh ssh

export PATH="/usr/local/Cellar/qt5/5.6.2/bin:$PATH"
upgradeImages () {
    SERVICE_CONTAINERS=`cat /repos/env/deploy/configurations/current/docker-compose-services.yaml | grep image | awk '{print $2}' | sort -u`
    CONTAINERS="$SERVICE_CONTAINERS `cat /repos/env/deploy/configurations/current/docker-compose.yaml | grep image | awk '{print $2}' | sort -u`"
    CONTAINERS="$CONTAINERS `cat /repos/env/deploy/configurations/current/docker-compose-master.yaml | grep image | awk '{print $2}' | sort -u`"
    CONTAINERS="$CONTAINERS `cat /repos/env/deploy/configurations/current/docker-compose-nflex.yaml | grep image | awk '{print $2}' | sort -u`"
    CONTAINERS="$CONTAINERS `cat /repos/env/deploy/configurations/current/docker-compose-extras.yaml | grep image | awk '{print $2}' | sort -u`"

    for image in ${CONTAINERS}; do   docker pull $image & done; wait
    docker images | awk '/none/ {print $3}' | xargs -r docker rmi -f
}
alias dockerrm="docker ps -aq | xargs docker rm -fv"
alias dockerrmv="docker volume ls -q | xargs docker volume rm -f"
alias dockerrminone="docker images | awk '/none/ {print $3}' | xargs docker rmi -f"

alias dockerclean="docker rmi $(docker images -q -f dangling=true)"
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

export REPO_LOCATION=~/projects/development
